name: Update Private Avrae Collections
on:
  push:
    branches:
      - testing
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: modified-files
      uses: jitterbit/get-changed-files@master
      with:
        format: 'json'
    - uses: 1drturtle/avrae-autoupdate@master
      with:
        avrae-token: '${{ secrets.AVRAE_TOKEN }}'
        collections_id_file_name: 'private_collections.json'
        gvars_id_file_name: 'private_gvars.json'
        modified-files: '${{ steps.modified-files.outputs.added_modified }}'
